name: CI Pipeline

on:
  push:
    branches:
      - main
      - CI
  pull_request:

jobs:
  sonarqube:
    environment: Dev
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json

      - name: Install Dependencies
        run: |
            cd ./frontend/MightyMammoths
            npm ci
      - name: Run Tests
        run: |
            cd ./frontend/MightyMammoths
            npm run test:unit
  e2e-test:
    runs-on: macos-latest
    name: E2E Test
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json

      - name: Install Dependencies
        run: |
            cd ./frontend/MightyMammoths
            npm ci

      - name: Install Detox Dependencies
        run: |
            brew tap wix/brew
            brew install applesimutils
            npm install -g detox-cli

      - name: Build E2E Tests
        run: |
            cd ./frontend/MightyMammoths
            npx detox build --configuration ios.sim.release
    
      - name: Run E2E Tests
        run: |
            cd ./frontend/MightyMammoths
            npx detox test --configuration ios.sim.release --headless

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json
      
      - name: "Install Dependencies"
        run: | 
          cd ./frontend/MightyMammoths  
          npm ci

      
      - name: "Run Lint"
        run: |
          cd ./frontend/MightyMammoths
          npm run lint
  