name: CI Pipeline

on:
  push:
    branches:
      - main
      - dev
      - tests
      - jscior/e2e
  pull_request:

jobs:
  sonarqube:
    needs: unit-test 
    environment: Dev
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json

      - name: Create env.tsx
        run: |
            echo "export const GOOGLE_MAPS_API_KEY = '${{ secrets.GOOGLE_MAPS_API_KEY }}';" > frontend/MightyMammoths/env.tsx

      - name: Install Dependencies
        run: |
            cd ./frontend/MightyMammoths
            npm ci
      - name: Run Tests with Coverage
        run: |
            cd ./frontend/MightyMammoths
            npm run test:unit -- --coverage
      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: frontend/MightyMammoths/coverage
            
  e2e-test:
    runs-on: macos-latest
    env:
      EXPO_NO_INTERACTIVE: 1
      EXPO_METRO_CACHE: 1
      NODE_OPTIONS: '--max_old_space_size=4096'
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json

      - name: Create env.tsx
        run: |
              echo "export const GOOGLE_MAPS_API_KEY = '${{ secrets.GOOGLE_MAPS_API_KEY }}';" > frontend/MightyMammoths/env.tsx
      
      - name: Install Global Dependencies
        run: |
          brew install watchman
          brew tap wix/brew
          brew install applesimutils
      
      - name: Install Project Dependencies
        run: |
          cd ./frontend/MightyMammoths
          npm ci
      
      - name: Prebuild Expo and Install CocoaPods
        run: |
          cd ./frontend/MightyMammoths
          npx expo prebuild --clean 
          cd ios
          pod install
      
      - name: Build App
        run: |
          cd ./frontend/MightyMammoths
          npx detox build --configuration ios.sim.release

      - name: Run E2E Tests
        run: |
          cd ./frontend/MightyMammoths
          npx jest --clearCache
          npx detox test --configuration ios.sim.release

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json
      
      - name: Create env.tsx
        run: |
              echo "export const GOOGLE_MAPS_API_KEY = '${{ secrets.GOOGLE_MAPS_API_KEY }}';" > frontend/MightyMammoths/env.tsx
      
      - name: "Install Dependencies"
        run: | 
          cd ./frontend/MightyMammoths  
          npm ci

      
      - name: "Run Lint"
        run: |
          cd ./frontend/MightyMammoths
          npm run lint
