name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  sonarqube:
    environment: Dev
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v4
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  unit-test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json

      - name: Install Dependencies
        run: |
            cd ./frontend/MightyMammoths
            npm ci
      - name: Run Tests
        run: |
            cd ./frontend/MightyMammoths
            npm run test:unit
            
  e2e-test:
    runs-on: macos-latest
    env:
      EXPO_NO_INTERACTIVE: 1
      DETOX_START_TIMEOUT: 60000

    name: E2E Test
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json

      - name: Navigate to Project Directory
        run: cd ./frontend/MightyMammoths

      - name: Install Watchman
        run: brew install watchman

      - name: Install Global Dependencies
        run: |
          npm install -g expo-cli
          npm install -g eas-cli
          npm install -g detox-cli

      - name: Install Project Dependencies
        run: |
          cd ./frontend/MightyMammoths
          npm ci

      - name: Install Detox Native Dependencies
        run: |
          brew tap wix/brew
          brew install applesimutils

      - name: Setup Expo
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          expo-version: latest
          token: "yOs41PeIKW3MVQlUO0JI2DRT_Ma_C_xcoD79E1b1"

      - name: Build iOS App for E2E Testing
        run: |
          cd ./frontend/MightyMammoths
          eas build --platform ios --non-interactive

      - name: Wait for Simulator to Boot
        run: sleep 30

      - name: Run Detox E2E Tests
        run: |
          cd ./frontend/MightyMammoths
          npx detox test --configuration ios.sim.release --headless

  lint:
    runs-on: ubuntu-latest
    name: Lint
    steps:
      - uses: actions/checkout@v4
      
      - name: "Setup Node.js"
        uses: actions/setup-node@v2
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ./frontend/MightyMammoths/package-lock.json
      
      - name: "Install Dependencies"
        run: | 
          cd ./frontend/MightyMammoths  
          npm ci

      
      - name: "Run Lint"
        run: |
          cd ./frontend/MightyMammoths
          npm run lint
  